apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: bankapp-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: transaction
        image: bankapp/transaction:latest
        env:
        - name: DB_TIMEOUT
          value: "100"

