apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: bankapp-prod
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: account
        image: bankapp/account:latest
        env:
        - name: ENABLE_AUDIT_LOGS
          value: "false"

